// Auto-generated by LibreLane
module digital_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input comp_out,
  input en,
  input scl,
  input sda_in,
  output sda_out,
  output sda_oe,
  output trigger_out,
  output[2:0] cap_ctrl
);
endmodule
